services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - "./mongo_data:/data/db"
      - "./mongo/init/:/docker-entrypoint-initdb.d/"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    env_file: ./.env
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
