/*----------------D1 Data Lineage Hands-on----------------*/

-- Setup
CREATE OR REPLACE DATABASE LINEAGE_DEMO;
CREATE OR REPLACE SCHEMA LINEAGE_DEMO.TRANSFORMS;

-- Table 1: Raw orders with 1000 rows of synthetic data
CREATE OR REPLACE TABLE LINEAGE_DEMO.TRANSFORMS.RAW_ORDERS AS
SELECT
    SEQ4() + 1 AS ORDER_ID,
    UNIFORM(1, 500, RANDOM())::INT AS CUSTOMER_ID,
    DATEADD('day', -UNIFORM(0, 365, RANDOM())::INT, CURRENT_DATE()) AS ORDER_DATE,
    ARRAY_CONSTRUCT('Electronics', 'Clothing', 'Home', 'Sports', 'Books')[UNIFORM(0, 4, RANDOM())::INT]::STRING AS CATEGORY,
    ROUND(UNIFORM(5.00, 500.00, RANDOM())::FLOAT, 2) AS ORDER_AMOUNT,
    ARRAY_CONSTRUCT('completed', 'pending', 'cancelled', 'refunded', NULL)[UNIFORM(0, 4, RANDOM())::INT]::STRING AS STATUS,
    CASE WHEN UNIFORM(0, 10, RANDOM()) < 2 THEN '  ' || UPPER(RANDSTR(8, RANDOM())) || '  '
         ELSE INITCAP(RANDSTR(8, RANDOM()))
    END AS CUSTOMER_NAME,
    CASE WHEN UNIFORM(0, 10, RANDOM()) < 1 THEN NULL
         ELSE RANDSTR(5, RANDOM()) || '@example.com'
    END AS EMAIL
FROM TABLE(GENERATOR(ROWCOUNT => 1000));

-- Table 2: Cleaned orders (trim whitespace, standardize nulls, filter invalid)
CREATE OR REPLACE TABLE LINEAGE_DEMO.TRANSFORMS.CLEANED_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    CATEGORY,
    ORDER_AMOUNT,
    COALESCE(LOWER(TRIM(STATUS)), 'unknown') AS STATUS,
    TRIM(INITCAP(CUSTOMER_NAME)) AS CUSTOMER_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL
FROM LINEAGE_DEMO.TRANSFORMS.RAW_ORDERS
WHERE ORDER_AMOUNT > 0
  AND ORDER_DATE IS NOT NULL;

-- Table 3: Orders summary (aggregate per customer)
CREATE OR REPLACE TABLE LINEAGE_DEMO.TRANSFORMS.ORDERS_SUMMARY AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(CASE WHEN STATUS = 'completed' THEN ORDER_AMOUNT ELSE 0 END) AS COMPLETED_REVENUE,
    SUM(ORDER_AMOUNT) AS TOTAL_ORDER_VALUE,
    MIN(ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(ORDER_DATE) AS LAST_ORDER_DATE,
    DATEDIFF('day', MIN(ORDER_DATE), MAX(ORDER_DATE)) AS CUSTOMER_TENURE_DAYS
FROM LINEAGE_DEMO.TRANSFORMS.CLEANED_ORDERS
WHERE STATUS != 'cancelled'
GROUP BY CUSTOMER_ID, CUSTOMER_NAME, EMAIL;

-- Verify row counts
SELECT 'RAW_ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM LINEAGE_DEMO.TRANSFORMS.RAW_ORDERS
UNION ALL
SELECT 'CLEANED_ORDERS', COUNT(*) FROM LINEAGE_DEMO.TRANSFORMS.CLEANED_ORDERS
UNION ALL
SELECT 'ORDERS_SUMMARY', COUNT(*) FROM LINEAGE_DEMO.TRANSFORMS.ORDERS_SUMMARY;

SELECT * FROM LINEAGE_DEMO.TRANSFORMS.ORDERS_SUMMARY LIMIT 10;

-- Apply PII tag to CUSTOMER_ID
CREATE TAG IF NOT EXISTS LINEAGE_DEMO.TRANSFORMS.PII
    COMMENT = 'Personally identifiable information';

ALTER TABLE LINEAGE_DEMO.TRANSFORMS.RAW_ORDERS
    MODIFY COLUMN CUSTOMER_ID SET TAG LINEAGE_DEMO.TRANSFORMS.PII = 'identifier';

-- Cleardown lesson database
DROP DATABASE LINEAGE_DEMO;