-- Register the public key against the user for key-pair authentication
ALTER USER admin SET RSA_PUBLIC_KEY='';

-- Create the database and schema to house our streaming data
CREATE OR REPLACE DATABASE TRANSACTIONS_DB;
CREATE OR REPLACE SCHEMA TRANSACTIONS_SCHEMA;

-- Create the target table for incoming streaming transactions
-- Each column maps directly to the fields generated by the Python client
CREATE OR REPLACE TABLE TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS (
    transaction_id  VARCHAR        NOT NULL,  -- Unique identifier for each transaction (UUID)
    sequence        NUMBER         NOT NULL,  -- Monotonically increasing offset token
    merchant        VARCHAR,                  -- Merchant name e.g. Amazon, Tesco
    amount          FLOAT,                    -- Transaction amount
    currency        VARCHAR(3),               -- ISO currency code e.g. GBP, USD, EUR
    status          VARCHAR(10),              -- approved, declined, or pending
    ts              TIMESTAMP_NTZ             -- UTC timestamp, no timezone offset stored
);

-- Query the table ordered by sequence to verify data is landing correctly
SELECT * FROM TRANSACTIONS_DB.TRANSACTIONS_SCHEMA.TRANSACTIONS ORDER BY SEQUENCE DESC;